version: "3.8"

services:
  db:
    container_name: 'news-backend-db'
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=news
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    networks:
      - news

  app:
    container_name: 'news-backend-app'
    build: .
    volumes:
      - .:/var/www/app
      - ./.docker/log:/var/log
    depends_on:
      - db
    networks:
      - news

  nginx:
    container_name: 'news-backend-nginx'
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    volumes:
      - .:/var/www/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - news

networks:
  news:
    driver: bridge
